# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/angel/codigo/kdevelop/stac

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/angel/codigo/kdevelop/stac

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/angel/codigo/kdevelop/stac/CMakeFiles /home/angel/codigo/kdevelop/stac/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/angel/codigo/kdevelop/stac/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stac

# Build rule for target.
stac: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stac
.PHONY : stac

# fast build rule for target.
stac/fast:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/build
.PHONY : stac/fast

cli.o: cli.cpp.o

.PHONY : cli.o

# target to build an object file
cli.cpp.o:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/cli.cpp.o
.PHONY : cli.cpp.o

cli.i: cli.cpp.i

.PHONY : cli.i

# target to preprocess a source file
cli.cpp.i:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/cli.cpp.i
.PHONY : cli.cpp.i

cli.s: cli.cpp.s

.PHONY : cli.s

# target to generate assembly for a file
cli.cpp.s:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/cli.cpp.s
.PHONY : cli.cpp.s

combinatoria.o: combinatoria.cpp.o

.PHONY : combinatoria.o

# target to build an object file
combinatoria.cpp.o:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/combinatoria.cpp.o
.PHONY : combinatoria.cpp.o

combinatoria.i: combinatoria.cpp.i

.PHONY : combinatoria.i

# target to preprocess a source file
combinatoria.cpp.i:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/combinatoria.cpp.i
.PHONY : combinatoria.cpp.i

combinatoria.s: combinatoria.cpp.s

.PHONY : combinatoria.s

# target to generate assembly for a file
combinatoria.cpp.s:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/combinatoria.cpp.s
.PHONY : combinatoria.cpp.s

distribucionesDiscretas.o: distribucionesDiscretas.cpp.o

.PHONY : distribucionesDiscretas.o

# target to build an object file
distribucionesDiscretas.cpp.o:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/distribucionesDiscretas.cpp.o
.PHONY : distribucionesDiscretas.cpp.o

distribucionesDiscretas.i: distribucionesDiscretas.cpp.i

.PHONY : distribucionesDiscretas.i

# target to preprocess a source file
distribucionesDiscretas.cpp.i:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/distribucionesDiscretas.cpp.i
.PHONY : distribucionesDiscretas.cpp.i

distribucionesDiscretas.s: distribucionesDiscretas.cpp.s

.PHONY : distribucionesDiscretas.s

# target to generate assembly for a file
distribucionesDiscretas.cpp.s:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/distribucionesDiscretas.cpp.s
.PHONY : distribucionesDiscretas.cpp.s

entradaYSalidaMatriz.o: entradaYSalidaMatriz.cpp.o

.PHONY : entradaYSalidaMatriz.o

# target to build an object file
entradaYSalidaMatriz.cpp.o:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/entradaYSalidaMatriz.cpp.o
.PHONY : entradaYSalidaMatriz.cpp.o

entradaYSalidaMatriz.i: entradaYSalidaMatriz.cpp.i

.PHONY : entradaYSalidaMatriz.i

# target to preprocess a source file
entradaYSalidaMatriz.cpp.i:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/entradaYSalidaMatriz.cpp.i
.PHONY : entradaYSalidaMatriz.cpp.i

entradaYSalidaMatriz.s: entradaYSalidaMatriz.cpp.s

.PHONY : entradaYSalidaMatriz.s

# target to generate assembly for a file
entradaYSalidaMatriz.cpp.s:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/entradaYSalidaMatriz.cpp.s
.PHONY : entradaYSalidaMatriz.cpp.s

funcMate.o: funcMate.cpp.o

.PHONY : funcMate.o

# target to build an object file
funcMate.cpp.o:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/funcMate.cpp.o
.PHONY : funcMate.cpp.o

funcMate.i: funcMate.cpp.i

.PHONY : funcMate.i

# target to preprocess a source file
funcMate.cpp.i:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/funcMate.cpp.i
.PHONY : funcMate.cpp.i

funcMate.s: funcMate.cpp.s

.PHONY : funcMate.s

# target to generate assembly for a file
funcMate.cpp.s:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/funcMate.cpp.s
.PHONY : funcMate.cpp.s

inteligenciArtificial.o: inteligenciArtificial.cpp.o

.PHONY : inteligenciArtificial.o

# target to build an object file
inteligenciArtificial.cpp.o:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/inteligenciArtificial.cpp.o
.PHONY : inteligenciArtificial.cpp.o

inteligenciArtificial.i: inteligenciArtificial.cpp.i

.PHONY : inteligenciArtificial.i

# target to preprocess a source file
inteligenciArtificial.cpp.i:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/inteligenciArtificial.cpp.i
.PHONY : inteligenciArtificial.cpp.i

inteligenciArtificial.s: inteligenciArtificial.cpp.s

.PHONY : inteligenciArtificial.s

# target to generate assembly for a file
inteligenciArtificial.cpp.s:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/inteligenciArtificial.cpp.s
.PHONY : inteligenciArtificial.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/main.cpp.s
.PHONY : main.cpp.s

matriz.o: matriz.cpp.o

.PHONY : matriz.o

# target to build an object file
matriz.cpp.o:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/matriz.cpp.o
.PHONY : matriz.cpp.o

matriz.i: matriz.cpp.i

.PHONY : matriz.i

# target to preprocess a source file
matriz.cpp.i:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/matriz.cpp.i
.PHONY : matriz.cpp.i

matriz.s: matriz.cpp.s

.PHONY : matriz.s

# target to generate assembly for a file
matriz.cpp.s:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/matriz.cpp.s
.PHONY : matriz.cpp.s

menUnaVariable.o: menUnaVariable.cpp.o

.PHONY : menUnaVariable.o

# target to build an object file
menUnaVariable.cpp.o:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/menUnaVariable.cpp.o
.PHONY : menUnaVariable.cpp.o

menUnaVariable.i: menUnaVariable.cpp.i

.PHONY : menUnaVariable.i

# target to preprocess a source file
menUnaVariable.cpp.i:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/menUnaVariable.cpp.i
.PHONY : menUnaVariable.cpp.i

menUnaVariable.s: menUnaVariable.cpp.s

.PHONY : menUnaVariable.s

# target to generate assembly for a file
menUnaVariable.cpp.s:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/menUnaVariable.cpp.s
.PHONY : menUnaVariable.cpp.s

menuCombinatoria.o: menuCombinatoria.cpp.o

.PHONY : menuCombinatoria.o

# target to build an object file
menuCombinatoria.cpp.o:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/menuCombinatoria.cpp.o
.PHONY : menuCombinatoria.cpp.o

menuCombinatoria.i: menuCombinatoria.cpp.i

.PHONY : menuCombinatoria.i

# target to preprocess a source file
menuCombinatoria.cpp.i:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/menuCombinatoria.cpp.i
.PHONY : menuCombinatoria.cpp.i

menuCombinatoria.s: menuCombinatoria.cpp.s

.PHONY : menuCombinatoria.s

# target to generate assembly for a file
menuCombinatoria.cpp.s:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/menuCombinatoria.cpp.s
.PHONY : menuCombinatoria.cpp.s

menuDistribDiscretas.o: menuDistribDiscretas.cpp.o

.PHONY : menuDistribDiscretas.o

# target to build an object file
menuDistribDiscretas.cpp.o:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/menuDistribDiscretas.cpp.o
.PHONY : menuDistribDiscretas.cpp.o

menuDistribDiscretas.i: menuDistribDiscretas.cpp.i

.PHONY : menuDistribDiscretas.i

# target to preprocess a source file
menuDistribDiscretas.cpp.i:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/menuDistribDiscretas.cpp.i
.PHONY : menuDistribDiscretas.cpp.i

menuDistribDiscretas.s: menuDistribDiscretas.cpp.s

.PHONY : menuDistribDiscretas.s

# target to generate assembly for a file
menuDistribDiscretas.cpp.s:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/menuDistribDiscretas.cpp.s
.PHONY : menuDistribDiscretas.cpp.s

menuDosVariables.o: menuDosVariables.cpp.o

.PHONY : menuDosVariables.o

# target to build an object file
menuDosVariables.cpp.o:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/menuDosVariables.cpp.o
.PHONY : menuDosVariables.cpp.o

menuDosVariables.i: menuDosVariables.cpp.i

.PHONY : menuDosVariables.i

# target to preprocess a source file
menuDosVariables.cpp.i:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/menuDosVariables.cpp.i
.PHONY : menuDosVariables.cpp.i

menuDosVariables.s: menuDosVariables.cpp.s

.PHONY : menuDosVariables.s

# target to generate assembly for a file
menuDosVariables.cpp.s:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/menuDosVariables.cpp.s
.PHONY : menuDosVariables.cpp.s

menuInteligenciArtificial.o: menuInteligenciArtificial.cpp.o

.PHONY : menuInteligenciArtificial.o

# target to build an object file
menuInteligenciArtificial.cpp.o:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/menuInteligenciArtificial.cpp.o
.PHONY : menuInteligenciArtificial.cpp.o

menuInteligenciArtificial.i: menuInteligenciArtificial.cpp.i

.PHONY : menuInteligenciArtificial.i

# target to preprocess a source file
menuInteligenciArtificial.cpp.i:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/menuInteligenciArtificial.cpp.i
.PHONY : menuInteligenciArtificial.cpp.i

menuInteligenciArtificial.s: menuInteligenciArtificial.cpp.s

.PHONY : menuInteligenciArtificial.s

# target to generate assembly for a file
menuInteligenciArtificial.cpp.s:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/menuInteligenciArtificial.cpp.s
.PHONY : menuInteligenciArtificial.cpp.s

menuMatrices.o: menuMatrices.cpp.o

.PHONY : menuMatrices.o

# target to build an object file
menuMatrices.cpp.o:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/menuMatrices.cpp.o
.PHONY : menuMatrices.cpp.o

menuMatrices.i: menuMatrices.cpp.i

.PHONY : menuMatrices.i

# target to preprocess a source file
menuMatrices.cpp.i:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/menuMatrices.cpp.i
.PHONY : menuMatrices.cpp.i

menuMatrices.s: menuMatrices.cpp.s

.PHONY : menuMatrices.s

# target to generate assembly for a file
menuMatrices.cpp.s:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/menuMatrices.cpp.s
.PHONY : menuMatrices.cpp.s

menuNVariables.o: menuNVariables.cpp.o

.PHONY : menuNVariables.o

# target to build an object file
menuNVariables.cpp.o:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/menuNVariables.cpp.o
.PHONY : menuNVariables.cpp.o

menuNVariables.i: menuNVariables.cpp.i

.PHONY : menuNVariables.i

# target to preprocess a source file
menuNVariables.cpp.i:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/menuNVariables.cpp.i
.PHONY : menuNVariables.cpp.i

menuNVariables.s: menuNVariables.cpp.s

.PHONY : menuNVariables.s

# target to generate assembly for a file
menuNVariables.cpp.s:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/menuNVariables.cpp.s
.PHONY : menuNVariables.cpp.s

menuSinDatos.o: menuSinDatos.cpp.o

.PHONY : menuSinDatos.o

# target to build an object file
menuSinDatos.cpp.o:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/menuSinDatos.cpp.o
.PHONY : menuSinDatos.cpp.o

menuSinDatos.i: menuSinDatos.cpp.i

.PHONY : menuSinDatos.i

# target to preprocess a source file
menuSinDatos.cpp.i:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/menuSinDatos.cpp.i
.PHONY : menuSinDatos.cpp.i

menuSinDatos.s: menuSinDatos.cpp.s

.PHONY : menuSinDatos.s

# target to generate assembly for a file
menuSinDatos.cpp.s:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/menuSinDatos.cpp.s
.PHONY : menuSinDatos.cpp.s

textosMenuPrincipal.o: textosMenuPrincipal.cpp.o

.PHONY : textosMenuPrincipal.o

# target to build an object file
textosMenuPrincipal.cpp.o:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/textosMenuPrincipal.cpp.o
.PHONY : textosMenuPrincipal.cpp.o

textosMenuPrincipal.i: textosMenuPrincipal.cpp.i

.PHONY : textosMenuPrincipal.i

# target to preprocess a source file
textosMenuPrincipal.cpp.i:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/textosMenuPrincipal.cpp.i
.PHONY : textosMenuPrincipal.cpp.i

textosMenuPrincipal.s: textosMenuPrincipal.cpp.s

.PHONY : textosMenuPrincipal.s

# target to generate assembly for a file
textosMenuPrincipal.cpp.s:
	$(MAKE) -f CMakeFiles/stac.dir/build.make CMakeFiles/stac.dir/textosMenuPrincipal.cpp.s
.PHONY : textosMenuPrincipal.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... stac"
	@echo "... cli.o"
	@echo "... cli.i"
	@echo "... cli.s"
	@echo "... combinatoria.o"
	@echo "... combinatoria.i"
	@echo "... combinatoria.s"
	@echo "... distribucionesDiscretas.o"
	@echo "... distribucionesDiscretas.i"
	@echo "... distribucionesDiscretas.s"
	@echo "... entradaYSalidaMatriz.o"
	@echo "... entradaYSalidaMatriz.i"
	@echo "... entradaYSalidaMatriz.s"
	@echo "... funcMate.o"
	@echo "... funcMate.i"
	@echo "... funcMate.s"
	@echo "... inteligenciArtificial.o"
	@echo "... inteligenciArtificial.i"
	@echo "... inteligenciArtificial.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... matriz.o"
	@echo "... matriz.i"
	@echo "... matriz.s"
	@echo "... menUnaVariable.o"
	@echo "... menUnaVariable.i"
	@echo "... menUnaVariable.s"
	@echo "... menuCombinatoria.o"
	@echo "... menuCombinatoria.i"
	@echo "... menuCombinatoria.s"
	@echo "... menuDistribDiscretas.o"
	@echo "... menuDistribDiscretas.i"
	@echo "... menuDistribDiscretas.s"
	@echo "... menuDosVariables.o"
	@echo "... menuDosVariables.i"
	@echo "... menuDosVariables.s"
	@echo "... menuInteligenciArtificial.o"
	@echo "... menuInteligenciArtificial.i"
	@echo "... menuInteligenciArtificial.s"
	@echo "... menuMatrices.o"
	@echo "... menuMatrices.i"
	@echo "... menuMatrices.s"
	@echo "... menuNVariables.o"
	@echo "... menuNVariables.i"
	@echo "... menuNVariables.s"
	@echo "... menuSinDatos.o"
	@echo "... menuSinDatos.i"
	@echo "... menuSinDatos.s"
	@echo "... textosMenuPrincipal.o"
	@echo "... textosMenuPrincipal.i"
	@echo "... textosMenuPrincipal.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

