# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/angel/codigo/kdevelop/stac

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/angel/codigo/kdevelop/stac

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/angel/codigo/kdevelop/stac/CMakeFiles /home/angel/codigo/kdevelop/stac/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/angel/codigo/kdevelop/stac/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stacPruebas

# Build rule for target.
stacPruebas: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stacPruebas
.PHONY : stacPruebas

# fast build rule for target.
stacPruebas/fast:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/build
.PHONY : stacPruebas/fast

calculos1Var.o: calculos1Var.cpp.o

.PHONY : calculos1Var.o

# target to build an object file
calculos1Var.cpp.o:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/calculos1Var.cpp.o
.PHONY : calculos1Var.cpp.o

calculos1Var.i: calculos1Var.cpp.i

.PHONY : calculos1Var.i

# target to preprocess a source file
calculos1Var.cpp.i:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/calculos1Var.cpp.i
.PHONY : calculos1Var.cpp.i

calculos1Var.s: calculos1Var.cpp.s

.PHONY : calculos1Var.s

# target to generate assembly for a file
calculos1Var.cpp.s:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/calculos1Var.cpp.s
.PHONY : calculos1Var.cpp.s

calculos2Var.o: calculos2Var.cpp.o

.PHONY : calculos2Var.o

# target to build an object file
calculos2Var.cpp.o:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/calculos2Var.cpp.o
.PHONY : calculos2Var.cpp.o

calculos2Var.i: calculos2Var.cpp.i

.PHONY : calculos2Var.i

# target to preprocess a source file
calculos2Var.cpp.i:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/calculos2Var.cpp.i
.PHONY : calculos2Var.cpp.i

calculos2Var.s: calculos2Var.cpp.s

.PHONY : calculos2Var.s

# target to generate assembly for a file
calculos2Var.cpp.s:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/calculos2Var.cpp.s
.PHONY : calculos2Var.cpp.s

calculosIA.o: calculosIA.cpp.o

.PHONY : calculosIA.o

# target to build an object file
calculosIA.cpp.o:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/calculosIA.cpp.o
.PHONY : calculosIA.cpp.o

calculosIA.i: calculosIA.cpp.i

.PHONY : calculosIA.i

# target to preprocess a source file
calculosIA.cpp.i:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/calculosIA.cpp.i
.PHONY : calculosIA.cpp.i

calculosIA.s: calculosIA.cpp.s

.PHONY : calculosIA.s

# target to generate assembly for a file
calculosIA.cpp.s:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/calculosIA.cpp.s
.PHONY : calculosIA.cpp.s

calculosMatriz.o: calculosMatriz.cpp.o

.PHONY : calculosMatriz.o

# target to build an object file
calculosMatriz.cpp.o:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/calculosMatriz.cpp.o
.PHONY : calculosMatriz.cpp.o

calculosMatriz.i: calculosMatriz.cpp.i

.PHONY : calculosMatriz.i

# target to preprocess a source file
calculosMatriz.cpp.i:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/calculosMatriz.cpp.i
.PHONY : calculosMatriz.cpp.i

calculosMatriz.s: calculosMatriz.cpp.s

.PHONY : calculosMatriz.s

# target to generate assembly for a file
calculosMatriz.cpp.s:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/calculosMatriz.cpp.s
.PHONY : calculosMatriz.cpp.s

calculosMuestreo.o: calculosMuestreo.cpp.o

.PHONY : calculosMuestreo.o

# target to build an object file
calculosMuestreo.cpp.o:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/calculosMuestreo.cpp.o
.PHONY : calculosMuestreo.cpp.o

calculosMuestreo.i: calculosMuestreo.cpp.i

.PHONY : calculosMuestreo.i

# target to preprocess a source file
calculosMuestreo.cpp.i:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/calculosMuestreo.cpp.i
.PHONY : calculosMuestreo.cpp.i

calculosMuestreo.s: calculosMuestreo.cpp.s

.PHONY : calculosMuestreo.s

# target to generate assembly for a file
calculosMuestreo.cpp.s:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/calculosMuestreo.cpp.s
.PHONY : calculosMuestreo.cpp.s

calculosNVar.o: calculosNVar.cpp.o

.PHONY : calculosNVar.o

# target to build an object file
calculosNVar.cpp.o:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/calculosNVar.cpp.o
.PHONY : calculosNVar.cpp.o

calculosNVar.i: calculosNVar.cpp.i

.PHONY : calculosNVar.i

# target to preprocess a source file
calculosNVar.cpp.i:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/calculosNVar.cpp.i
.PHONY : calculosNVar.cpp.i

calculosNVar.s: calculosNVar.cpp.s

.PHONY : calculosNVar.s

# target to generate assembly for a file
calculosNVar.cpp.s:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/calculosNVar.cpp.s
.PHONY : calculosNVar.cpp.s

cli.o: cli.cpp.o

.PHONY : cli.o

# target to build an object file
cli.cpp.o:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/cli.cpp.o
.PHONY : cli.cpp.o

cli.i: cli.cpp.i

.PHONY : cli.i

# target to preprocess a source file
cli.cpp.i:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/cli.cpp.i
.PHONY : cli.cpp.i

cli.s: cli.cpp.s

.PHONY : cli.s

# target to generate assembly for a file
cli.cpp.s:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/cli.cpp.s
.PHONY : cli.cpp.s

combinatoria.o: combinatoria.cpp.o

.PHONY : combinatoria.o

# target to build an object file
combinatoria.cpp.o:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/combinatoria.cpp.o
.PHONY : combinatoria.cpp.o

combinatoria.i: combinatoria.cpp.i

.PHONY : combinatoria.i

# target to preprocess a source file
combinatoria.cpp.i:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/combinatoria.cpp.i
.PHONY : combinatoria.cpp.i

combinatoria.s: combinatoria.cpp.s

.PHONY : combinatoria.s

# target to generate assembly for a file
combinatoria.cpp.s:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/combinatoria.cpp.s
.PHONY : combinatoria.cpp.s

distribucionesDiscretas.o: distribucionesDiscretas.cpp.o

.PHONY : distribucionesDiscretas.o

# target to build an object file
distribucionesDiscretas.cpp.o:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/distribucionesDiscretas.cpp.o
.PHONY : distribucionesDiscretas.cpp.o

distribucionesDiscretas.i: distribucionesDiscretas.cpp.i

.PHONY : distribucionesDiscretas.i

# target to preprocess a source file
distribucionesDiscretas.cpp.i:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/distribucionesDiscretas.cpp.i
.PHONY : distribucionesDiscretas.cpp.i

distribucionesDiscretas.s: distribucionesDiscretas.cpp.s

.PHONY : distribucionesDiscretas.s

# target to generate assembly for a file
distribucionesDiscretas.cpp.s:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/distribucionesDiscretas.cpp.s
.PHONY : distribucionesDiscretas.cpp.s

funcDatosBasicas.o: funcDatosBasicas.cpp.o

.PHONY : funcDatosBasicas.o

# target to build an object file
funcDatosBasicas.cpp.o:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/funcDatosBasicas.cpp.o
.PHONY : funcDatosBasicas.cpp.o

funcDatosBasicas.i: funcDatosBasicas.cpp.i

.PHONY : funcDatosBasicas.i

# target to preprocess a source file
funcDatosBasicas.cpp.i:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/funcDatosBasicas.cpp.i
.PHONY : funcDatosBasicas.cpp.i

funcDatosBasicas.s: funcDatosBasicas.cpp.s

.PHONY : funcDatosBasicas.s

# target to generate assembly for a file
funcDatosBasicas.cpp.s:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/funcDatosBasicas.cpp.s
.PHONY : funcDatosBasicas.cpp.s

funcMatematicasBasicas.o: funcMatematicasBasicas.cpp.o

.PHONY : funcMatematicasBasicas.o

# target to build an object file
funcMatematicasBasicas.cpp.o:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/funcMatematicasBasicas.cpp.o
.PHONY : funcMatematicasBasicas.cpp.o

funcMatematicasBasicas.i: funcMatematicasBasicas.cpp.i

.PHONY : funcMatematicasBasicas.i

# target to preprocess a source file
funcMatematicasBasicas.cpp.i:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/funcMatematicasBasicas.cpp.i
.PHONY : funcMatematicasBasicas.cpp.i

funcMatematicasBasicas.s: funcMatematicasBasicas.cpp.s

.PHONY : funcMatematicasBasicas.s

# target to generate assembly for a file
funcMatematicasBasicas.cpp.s:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/funcMatematicasBasicas.cpp.s
.PHONY : funcMatematicasBasicas.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/main.cpp.s
.PHONY : main.cpp.s

menu1Var.o: menu1Var.cpp.o

.PHONY : menu1Var.o

# target to build an object file
menu1Var.cpp.o:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/menu1Var.cpp.o
.PHONY : menu1Var.cpp.o

menu1Var.i: menu1Var.cpp.i

.PHONY : menu1Var.i

# target to preprocess a source file
menu1Var.cpp.i:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/menu1Var.cpp.i
.PHONY : menu1Var.cpp.i

menu1Var.s: menu1Var.cpp.s

.PHONY : menu1Var.s

# target to generate assembly for a file
menu1Var.cpp.s:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/menu1Var.cpp.s
.PHONY : menu1Var.cpp.s

menu2Var.o: menu2Var.cpp.o

.PHONY : menu2Var.o

# target to build an object file
menu2Var.cpp.o:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/menu2Var.cpp.o
.PHONY : menu2Var.cpp.o

menu2Var.i: menu2Var.cpp.i

.PHONY : menu2Var.i

# target to preprocess a source file
menu2Var.cpp.i:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/menu2Var.cpp.i
.PHONY : menu2Var.cpp.i

menu2Var.s: menu2Var.cpp.s

.PHONY : menu2Var.s

# target to generate assembly for a file
menu2Var.cpp.s:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/menu2Var.cpp.s
.PHONY : menu2Var.cpp.s

menuCombinatoria.o: menuCombinatoria.cpp.o

.PHONY : menuCombinatoria.o

# target to build an object file
menuCombinatoria.cpp.o:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/menuCombinatoria.cpp.o
.PHONY : menuCombinatoria.cpp.o

menuCombinatoria.i: menuCombinatoria.cpp.i

.PHONY : menuCombinatoria.i

# target to preprocess a source file
menuCombinatoria.cpp.i:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/menuCombinatoria.cpp.i
.PHONY : menuCombinatoria.cpp.i

menuCombinatoria.s: menuCombinatoria.cpp.s

.PHONY : menuCombinatoria.s

# target to generate assembly for a file
menuCombinatoria.cpp.s:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/menuCombinatoria.cpp.s
.PHONY : menuCombinatoria.cpp.s

menuDistribDiscretas.o: menuDistribDiscretas.cpp.o

.PHONY : menuDistribDiscretas.o

# target to build an object file
menuDistribDiscretas.cpp.o:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/menuDistribDiscretas.cpp.o
.PHONY : menuDistribDiscretas.cpp.o

menuDistribDiscretas.i: menuDistribDiscretas.cpp.i

.PHONY : menuDistribDiscretas.i

# target to preprocess a source file
menuDistribDiscretas.cpp.i:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/menuDistribDiscretas.cpp.i
.PHONY : menuDistribDiscretas.cpp.i

menuDistribDiscretas.s: menuDistribDiscretas.cpp.s

.PHONY : menuDistribDiscretas.s

# target to generate assembly for a file
menuDistribDiscretas.cpp.s:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/menuDistribDiscretas.cpp.s
.PHONY : menuDistribDiscretas.cpp.s

menuIA.o: menuIA.cpp.o

.PHONY : menuIA.o

# target to build an object file
menuIA.cpp.o:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/menuIA.cpp.o
.PHONY : menuIA.cpp.o

menuIA.i: menuIA.cpp.i

.PHONY : menuIA.i

# target to preprocess a source file
menuIA.cpp.i:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/menuIA.cpp.i
.PHONY : menuIA.cpp.i

menuIA.s: menuIA.cpp.s

.PHONY : menuIA.s

# target to generate assembly for a file
menuIA.cpp.s:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/menuIA.cpp.s
.PHONY : menuIA.cpp.s

menuMatrices.o: menuMatrices.cpp.o

.PHONY : menuMatrices.o

# target to build an object file
menuMatrices.cpp.o:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/menuMatrices.cpp.o
.PHONY : menuMatrices.cpp.o

menuMatrices.i: menuMatrices.cpp.i

.PHONY : menuMatrices.i

# target to preprocess a source file
menuMatrices.cpp.i:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/menuMatrices.cpp.i
.PHONY : menuMatrices.cpp.i

menuMatrices.s: menuMatrices.cpp.s

.PHONY : menuMatrices.s

# target to generate assembly for a file
menuMatrices.cpp.s:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/menuMatrices.cpp.s
.PHONY : menuMatrices.cpp.s

menuNVar.o: menuNVar.cpp.o

.PHONY : menuNVar.o

# target to build an object file
menuNVar.cpp.o:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/menuNVar.cpp.o
.PHONY : menuNVar.cpp.o

menuNVar.i: menuNVar.cpp.i

.PHONY : menuNVar.i

# target to preprocess a source file
menuNVar.cpp.i:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/menuNVar.cpp.i
.PHONY : menuNVar.cpp.i

menuNVar.s: menuNVar.cpp.s

.PHONY : menuNVar.s

# target to generate assembly for a file
menuNVar.cpp.s:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/menuNVar.cpp.s
.PHONY : menuNVar.cpp.s

menuSinDatos.o: menuSinDatos.cpp.o

.PHONY : menuSinDatos.o

# target to build an object file
menuSinDatos.cpp.o:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/menuSinDatos.cpp.o
.PHONY : menuSinDatos.cpp.o

menuSinDatos.i: menuSinDatos.cpp.i

.PHONY : menuSinDatos.i

# target to preprocess a source file
menuSinDatos.cpp.i:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/menuSinDatos.cpp.i
.PHONY : menuSinDatos.cpp.i

menuSinDatos.s: menuSinDatos.cpp.s

.PHONY : menuSinDatos.s

# target to generate assembly for a file
menuSinDatos.cpp.s:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/menuSinDatos.cpp.s
.PHONY : menuSinDatos.cpp.s

menuTablasCont.o: menuTablasCont.cpp.o

.PHONY : menuTablasCont.o

# target to build an object file
menuTablasCont.cpp.o:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/menuTablasCont.cpp.o
.PHONY : menuTablasCont.cpp.o

menuTablasCont.i: menuTablasCont.cpp.i

.PHONY : menuTablasCont.i

# target to preprocess a source file
menuTablasCont.cpp.i:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/menuTablasCont.cpp.i
.PHONY : menuTablasCont.cpp.i

menuTablasCont.s: menuTablasCont.cpp.s

.PHONY : menuTablasCont.s

# target to generate assembly for a file
menuTablasCont.cpp.s:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/menuTablasCont.cpp.s
.PHONY : menuTablasCont.cpp.s

muestreo.o: muestreo.cpp.o

.PHONY : muestreo.o

# target to build an object file
muestreo.cpp.o:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/muestreo.cpp.o
.PHONY : muestreo.cpp.o

muestreo.i: muestreo.cpp.i

.PHONY : muestreo.i

# target to preprocess a source file
muestreo.cpp.i:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/muestreo.cpp.i
.PHONY : muestreo.cpp.i

muestreo.s: muestreo.cpp.s

.PHONY : muestreo.s

# target to generate assembly for a file
muestreo.cpp.s:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/muestreo.cpp.s
.PHONY : muestreo.cpp.s

textosMenus.o: textosMenus.cpp.o

.PHONY : textosMenus.o

# target to build an object file
textosMenus.cpp.o:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/textosMenus.cpp.o
.PHONY : textosMenus.cpp.o

textosMenus.i: textosMenus.cpp.i

.PHONY : textosMenus.i

# target to preprocess a source file
textosMenus.cpp.i:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/textosMenus.cpp.i
.PHONY : textosMenus.cpp.i

textosMenus.s: textosMenus.cpp.s

.PHONY : textosMenus.s

# target to generate assembly for a file
textosMenus.cpp.s:
	$(MAKE) -f CMakeFiles/stacPruebas.dir/build.make CMakeFiles/stacPruebas.dir/textosMenus.cpp.s
.PHONY : textosMenus.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... stacPruebas"
	@echo "... calculos1Var.o"
	@echo "... calculos1Var.i"
	@echo "... calculos1Var.s"
	@echo "... calculos2Var.o"
	@echo "... calculos2Var.i"
	@echo "... calculos2Var.s"
	@echo "... calculosIA.o"
	@echo "... calculosIA.i"
	@echo "... calculosIA.s"
	@echo "... calculosMatriz.o"
	@echo "... calculosMatriz.i"
	@echo "... calculosMatriz.s"
	@echo "... calculosMuestreo.o"
	@echo "... calculosMuestreo.i"
	@echo "... calculosMuestreo.s"
	@echo "... calculosNVar.o"
	@echo "... calculosNVar.i"
	@echo "... calculosNVar.s"
	@echo "... cli.o"
	@echo "... cli.i"
	@echo "... cli.s"
	@echo "... combinatoria.o"
	@echo "... combinatoria.i"
	@echo "... combinatoria.s"
	@echo "... distribucionesDiscretas.o"
	@echo "... distribucionesDiscretas.i"
	@echo "... distribucionesDiscretas.s"
	@echo "... funcDatosBasicas.o"
	@echo "... funcDatosBasicas.i"
	@echo "... funcDatosBasicas.s"
	@echo "... funcMatematicasBasicas.o"
	@echo "... funcMatematicasBasicas.i"
	@echo "... funcMatematicasBasicas.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... menu1Var.o"
	@echo "... menu1Var.i"
	@echo "... menu1Var.s"
	@echo "... menu2Var.o"
	@echo "... menu2Var.i"
	@echo "... menu2Var.s"
	@echo "... menuCombinatoria.o"
	@echo "... menuCombinatoria.i"
	@echo "... menuCombinatoria.s"
	@echo "... menuDistribDiscretas.o"
	@echo "... menuDistribDiscretas.i"
	@echo "... menuDistribDiscretas.s"
	@echo "... menuIA.o"
	@echo "... menuIA.i"
	@echo "... menuIA.s"
	@echo "... menuMatrices.o"
	@echo "... menuMatrices.i"
	@echo "... menuMatrices.s"
	@echo "... menuNVar.o"
	@echo "... menuNVar.i"
	@echo "... menuNVar.s"
	@echo "... menuSinDatos.o"
	@echo "... menuSinDatos.i"
	@echo "... menuSinDatos.s"
	@echo "... menuTablasCont.o"
	@echo "... menuTablasCont.i"
	@echo "... menuTablasCont.s"
	@echo "... muestreo.o"
	@echo "... muestreo.i"
	@echo "... muestreo.s"
	@echo "... textosMenus.o"
	@echo "... textosMenus.i"
	@echo "... textosMenus.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

